name: buildtest 
on:
  push:
    branches:
      - zensical-test
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: pip install zensical
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - run: npm ci
      - run: npm run build-ts
      - run: zensical build --clean
      - uses: actions/upload-artifact@v4
        with:
          name: buildtest
          path: site
